#!/usr/bin/env python3
"""Builds the HardLine icon and logo files.

Run it through build.sh, which supplies the font and the renderer:
    build.py FONTS_DIR REPO_DIR

The icon is described once, on the 108-unit grid of an Android adaptive icon (the middle 72 units
are what a launcher shows, the middle 66 are always visible), and written out from that one
description as SVG and PNG into branding/, as vector drawables into the app's resources, and as
the store listing images into fastlane/. The wordmark goes into the app too, one drawable per run.
"""
import sys
from pathlib import Path

import cairosvg
import uharfbuzz as hb
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

WHITE, SIGNAL, DARK = "#FFFFFF", "#FF5A1F", "#18181B"
FONT = "barlow-condensed-600"
# The wordmark: (text, tracking in em[, own colour]).
RUNS = [("HARD", 0.06), ("LINE", 0.06, SIGNAL)]


def n(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def circle(cx, cy, r):
    return f"M{n(cx - r)},{n(cy)}a{n(r)},{n(r)} 0 1,0 {n(2 * r)},0a{n(r)},{n(r)} 0 1,0 {n(-2 * r)},0z"


def rrect(x, y, w, h, r):
    a = f"a{n(r)},{n(r)} 0 0,1 "
    return (
        f"M{n(x + r)},{n(y)}h{n(w - 2 * r)}{a}{n(r)},{n(r)}v{n(h - 2 * r)}{a}{n(-r)},{n(r)}"
        f"h{n(2 * r - w)}{a}{n(-r)},{n(-r)}v{n(2 * r - h)}{a}{n(r)},{n(-r)}z"
    )


def fill(d, color, evenodd=False):
    return {"d": d, "fill": color, "evenodd": evenodd}


def stroke(d, color, width, cap="butt", join="round"):
    return {"d": d, "stroke": color, "width": width, "cap": cap, "join": join}


# ---------------------------------------------------------------------------------- the drawing

CAMERA = (37, 37, 34)       # the square camera: left, top, size; it sits in the middle of the icon
CABLE_Y, CABLE_WIDTH = 54, 8


def cable(x0):
    """The cable, from x0 to just under the camera's edge."""
    return f"M{n(x0)},{CABLE_Y}H{n(CAMERA[0] + 2)}"


def drawing(cable_from=-8):
    """The icon's foreground, back to front, and its single-colour version (colours are ignored there)."""
    x, y, size = CAMERA
    cx, cy, k = x + size / 2, y + size / 2, size / 34
    box = rrect(x, y, size, size, 6 * k)
    layers = [
        stroke(cable(cable_from), SIGNAL, CABLE_WIDTH),
        fill(box, WHITE),
        stroke(circle(cx, cy, 9 * k), DARK, 4.5 * k, cap="round"),
        fill(circle(cx, cy, 3.8 * k), SIGNAL),
    ]
    mono = [
        stroke(cable(cable_from), WHITE, CABLE_WIDTH),
        fill(box + circle(cx, cy, 11.25 * k) + circle(cx, cy, 6.75 * k), WHITE, evenodd=True),
    ]
    return layers, mono


LAYERS, MONO = drawing()
# The notification icon shows this part of the grid, so that the camera fills most of its 24 dp.
STATUS_WINDOW = (22, 27, 54)


# ---------------------------------------------------------------------------------- icon

def svg_paths(layers, color=None):
    out = []
    for l in layers:
        if "fill" in l:
            rule = ' fill-rule="evenodd"' if l["evenodd"] else ""
            out.append(f'<path d="{l["d"]}" fill="{color or l["fill"]}"{rule}/>')
        else:
            out.append(
                f'<path d="{l["d"]}" fill="none" stroke="{color or l["stroke"]}" stroke-width="{n(l["width"])}" '
                f'stroke-linecap="{l["cap"]}" stroke-linejoin="{l["join"]}"/>'
            )
    return "".join(out)


def icon_svg(size=512):
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="18 18 72 72" width="{size}" height="{size}">'
        f'<rect x="18" y="18" width="72" height="72" fill="{DARK}"/>{svg_paths(LAYERS)}</svg>'
    )


def layer_svg(layers, color=None):
    return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108" width="432" height="432">{svg_paths(layers, color)}</svg>'


def vector_paths(layers, color, indent):
    out = []
    for l in layers:
        if "fill" in l:
            rule = ' android:fillType="evenOdd"' if l["evenodd"] else ""
            out.append(f'{indent}<path android:fillColor="{color or l["fill"]}"{rule} android:pathData="{l["d"]}" />')
        else:
            out.append(
                f'{indent}<path android:strokeColor="{color or l["stroke"]}" android:strokeWidth="{n(l["width"])}" '
                f'android:strokeLineCap="{l["cap"]}" android:strokeLineJoin="{l["join"]}" android:pathData="{l["d"]}" />'
            )
    return out


GENERATED = "<!-- Generated by branding/build.sh. Edit branding/build.py instead. -->"


def vector_drawable(layers, color=None):
    out = [
        '<?xml version="1.0" encoding="utf-8"?>',
        GENERATED,
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">',
    ]
    out += vector_paths(layers, color, "    ")
    out.append("</vector>")
    return "\n".join(out) + "\n"


def status_drawable(layers, window, dp=24):
    """The single-colour drawing, cropped to a square window of the grid, as a notification icon."""
    x, y, size = window
    k = dp / size
    out = [
        '<?xml version="1.0" encoding="utf-8"?>',
        GENERATED,
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        f'    android:width="{dp}dp" android:height="{dp}dp" android:viewportWidth="{dp}" android:viewportHeight="{dp}">',
        f'    <group android:scaleX="{k:.5f}" android:scaleY="{k:.5f}" android:translateX="{-x * k:.4f}" android:translateY="{-y * k:.4f}">',
    ]
    out += vector_paths(layers, WHITE, "        ")
    out += ["    </group>", "</vector>"]
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------- wordmark

def outline(text, font_file, size, tracking, x0):
    """The text as one path with its baseline on y = 0, starting at x0. Returns (path, end x, cap height, bounds)."""
    tt = TTFont(font_file)
    glyphs, upm = tt.getGlyphSet(), tt["head"].unitsPerEm
    scale = size / upm
    font = hb.Font(hb.Face(hb.Blob.from_file_path(str(font_file))))
    buf = hb.Buffer()
    buf.add_str(text)
    buf.guess_segment_properties()
    hb.shape(font, buf, {"kern": True})
    x, parts, bounds = x0 / scale, [], None
    for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
        glyph = glyphs[tt.getGlyphName(info.codepoint)]
        place = (scale, 0, 0, -scale, (x + pos.x_offset) * scale, -pos.y_offset * scale)
        pen = SVGPathPen(glyphs, ntos=n)
        glyph.draw(TransformPen(pen, place))
        parts.append(pen.getCommands())
        box = BoundsPen(glyphs)
        glyph.draw(TransformPen(box, place))
        if box.bounds:
            b = box.bounds
            bounds = b if bounds is None else (min(bounds[0], b[0]), min(bounds[1], b[1]), max(bounds[2], b[2]), max(bounds[3], b[3]))
        x += pos.x_advance + tracking * upm
    return "".join(parts), (x - tracking * upm) * scale, tt["OS/2"].sCapHeight * scale, bounds


def wordmark(font_file, size):
    """The runs set one after another. Returns ([(path, own colour or None)], width, cap height, bounds)."""
    x, parts, cap, bounds = 0.0, [], 0.0, None
    for i, (text, tracking, *own) in enumerate(RUNS):
        d, x, cap, box = outline(text, font_file, size, tracking, x)
        if i < len(RUNS) - 1:
            x += tracking * size
        parts.append((d, own[0] if own else None))
        if box:
            bounds = box if bounds is None else (min(bounds[0], box[0]), min(bounds[1], box[1]), max(bounds[2], box[2]), max(bounds[3], box[3]))
    return parts, x, cap, bounds


def run_paths(parts, color):
    return "".join(f'<path d="{d}" fill="{own or color}"/>' for d, own in parts)


def wordmark_svg(parts, bounds, color, pad=2):
    x0, y0, x1, y1 = bounds
    w, h = x1 - x0 + 2 * pad, y1 - y0 + 2 * pad
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{n(x0 - pad)} {n(y0 - pad)} {n(w)} {n(h)}" '
        f'width="{n(w * 4)}" height="{n(h * 4)}">{run_paths(parts, color)}</svg>'
    )


def run_drawable(parts, bounds, index, dp=18):
    """One run of the wordmark as a white drawable, in the viewport of the whole wordmark so that the
    runs line up when the app stacks them and tints each one."""
    x0, y0, x1, y1 = bounds
    w, h = x1 - x0, y1 - y0
    return "\n".join([
        '<?xml version="1.0" encoding="utf-8"?>',
        GENERATED,
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        f'    android:width="{n(dp * w / h)}dp" android:height="{dp}dp" android:viewportWidth="{n(w)}" android:viewportHeight="{n(h)}">',
        f'    <group android:translateX="{n(-x0)}" android:translateY="{n(-y0)}">',
        f'        <path android:fillColor="{WHITE}" android:pathData="{parts[index][0]}" />',
        "    </group>",
        "</vector>",
    ]) + "\n"


def logo_svg(parts, width, cap, color, edge="none", tile=64, gap=18):
    """The icon as a rounded tile with the wordmark beside it, centred on the capital letters."""
    k = tile / 72
    total = tile + gap + width + 2
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {n(total)} {tile}" width="{n(total * 4)}" height="{tile * 4}">'
        f'<clipPath id="tile"><rect width="{tile}" height="{tile}" rx="{n(tile * 0.225)}"/></clipPath>'
        f'<g clip-path="url(#tile)"><rect width="{tile}" height="{tile}" fill="{DARK}"/>'
        f'<g transform="scale({n(k)}) translate(-18 -18)">{svg_paths(LAYERS)}</g></g>'
        f'<rect x="0.5" y="0.5" width="{tile - 1}" height="{tile - 1}" rx="{n(tile * 0.225 - 0.5)}" fill="none" stroke="{edge}"/>'
        f'<g transform="translate({tile + gap} {n(tile / 2 + cap / 2)})">{run_paths(parts, color)}</g></svg>'
    )


def banner_svg(parts, width, cap, w, h):
    """The drawing with its cable coming in from the left edge, and the wordmark beside it."""
    x, y, size = CAMERA
    k = h * 0.34 / size                                   # the camera is a third of the height
    left = w * 0.26
    tx, ty = left - x * k, h / 2 - CABLE_Y * k
    layers, _ = drawing(cable_from=-tx / k - 1)
    gap = size * k * 0.42
    text_x = left + size * k + gap
    s = min((w - text_x - w * 0.09) / width, size * k * 0.62 / cap)
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}">'
        f'<rect width="{w}" height="{h}" fill="{DARK}"/>'
        f'<g transform="translate({n(tx)} {n(ty)}) scale({n(k)})">{svg_paths(layers)}</g>'
        f'<g transform="translate({n(text_x)} {n(h / 2 + cap * s / 2)}) scale({n(s)})">{run_paths(parts, WHITE)}</g></svg>'
    )


# ---------------------------------------------------------------------------------- output

def main():
    fonts, repo = Path(sys.argv[1]), Path(sys.argv[2])
    brand, res, store = repo / "branding", repo / "app/src/main/res", repo / "fastlane/metadata/android/en-US/images"
    parts, width, cap, bounds = wordmark(fonts / FONT / "font.ttf", 34)
    text = {
        brand / "icon.svg": icon_svg(),
        brand / "icon-foreground.svg": layer_svg(LAYERS),
        brand / "icon-monochrome.svg": layer_svg(MONO, "#000000"),
        brand / "wordmark.svg": wordmark_svg(parts, bounds, DARK),
        brand / "wordmark-dark.svg": wordmark_svg(parts, bounds, WHITE),
        brand / "logo.svg": logo_svg(parts, width, cap, DARK),
        brand / "logo-dark.svg": logo_svg(parts, width, cap, WHITE, edge="rgba(255,255,255,0.16)"),
        brand / "banner.svg": banner_svg(parts, width, cap, 1280, 640),
        res / "drawable/ic_launcher_foreground.xml": vector_drawable(LAYERS),
        res / "drawable/ic_launcher_monochrome.xml": vector_drawable(MONO, WHITE),
        res / "drawable/ic_stat_camera.xml": status_drawable(MONO, STATUS_WINDOW),
        **{res / f"drawable/wordmark_{run[0].lower()}.xml": run_drawable(parts, bounds, i) for i, run in enumerate(RUNS)},
        res / "values/ic_launcher_background.xml":
            f'<?xml version="1.0" encoding="utf-8"?>\n{GENERATED}\n<resources>\n    <color name="ic_launcher_background">{DARK}</color>\n</resources>\n',
    }
    for path, content in text.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    images = {
        brand / "icon-512.png": (text[brand / "icon.svg"], 512),
        brand / "logo.png": (text[brand / "logo.svg"], None),
        brand / "logo-dark.png": (text[brand / "logo-dark.svg"], None),
        brand / "banner.png": (text[brand / "banner.svg"], 1280),
        store / "icon.png": (text[brand / "icon.svg"], 512),
        store / "featureGraphic.png": (banner_svg(parts, width, cap, 1024, 500), 1024),
    }
    for path, (svg, px) in images.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        cairosvg.svg2png(bytestring=svg.encode(), write_to=str(path), output_width=px)
    for path in list(text) + list(images):
        print(path.relative_to(repo))


if __name__ == "__main__":
    main()
